-- CRIME REPORTING SYSTEM CASE STUDY
CREATE DATABASE CrimeReportingSystemCaseStudy;
USE CrimeReportingSystemCaseStudy;
-- SQL Schema
CREATE TABLE Victims(
	VictimID INT PRIMARY KEY,
	FirstName VARCHAR(255) NOT NULL, 
	LastName VARCHAR(255) NOT NULL,
	DateOfBirth DATE NOT NULL,
	Gender CHAR(1) NOT NULL,
	ContactInfo VARCHAR(255) NOT NULL
);
CREATE TABLE Suspects(
	SuspectID INT PRIMARY KEY,
	FirstName VARCHAR(255) NOT NULL, 
	LastName VARCHAR(255) NOT NULL,
	DateOfBirth DATE NOT NULL,
	Gender CHAR(1) NOT NULL,
	ContactInfo VARCHAR(255) NOT NULL
);
CREATE TABLE Incidents(
	IncidentID INT PRIMARY KEY,
	IncidentType VARCHAR(255) NOT NULL,
	IncidentDate DATE NOT NULL,
	Location VARCHAR(255) NOT NULL,
	Description TEXT NOT NULL,
	Status VARCHAR(20) NOT NULL,
	VictimID INT NOT NULL,
	SuspectID INT NOT NULL,
	FOREIGN KEY(VictimID) REFERENCES Victims(VictimID) ON DELETE CASCADE,
	FOREIGN KEY(SuspectID) REFERENCES Suspects(SuspectID) ON DELETE CASCADE
);
CREATE TABLE LawEnforcementAgencies(
	AgencyID INT PRIMARY KEY,
	AgencyName VARCHAR(255) NOT NULL,
	Jurisdiction VARCHAR(255) NOT NULL, 
	ContactInfo VARCHAR(255) NOT NULL
);
CREATE TABLE Officers(
	OfficerID INT PRIMARY KEY,
	FirstName VARCHAR(255) NOT NULL, 
	LastName VARCHAR(255) NOT NULL,
	BadgeNumber INT UNIQUE NOT NULL,
	Rank INT NOT NULL,
	ContactInfo VARCHAR(255) NOT NULL,
	AgencyID INT NOT NULL,
	FOREIGN KEY(AgencyID) REFERENCES LawEnforcementAgencies(AgencyID) ON DELETE CASCADE
);
CREATE TABLE Evidence(
	EvidenceID INT PRIMARY KEY,
	Description TEXT NOT NULL,
	LocationFound VARCHAR(255) NOT NULL,
	IncidentID INT NOT NULL,
	FOREIGN KEY(IncidentID) REFERENCES Incidents(IncidentID) ON DELETE CASCADE
);
CREATE TABLE Reports(
	ReportID INT PRIMARY KEY,
	IncidentID INT NOT NULL,
	ReportingOfficerID INT NOT NULL,
	ReportDate DATE NOT NULL,
	ReportDetails VARCHAR(255) NOT NULL,
	Status VARCHAR(20) NOT NULL,
	FOREIGN KEY(IncidentID) REFERENCES Incidents(IncidentID) ON DELETE CASCADE,
	FOREIGN KEY(ReportingOfficerID) REFERENCES Officers(OfficerID) ON DELETE CASCADE
);