-- VIRTUAL ART GALLERY CASE STUDY
CREATE DATABASE VirtualArtGalleryCaseStudy;
USE VirtualArtGalleryCaseStudy;
-- SQL Schema
CREATE TABLE Artist(
	ArtistID INT PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Biography TEXT NOT NULL,
	BirthDate DATE NOT NULL,
	Nationality VARCHAR(100) NOT NULL,
	Website VARCHAR(255) UNIQUE NOT NULL,
	ContactInformation VARCHAR(255) UNIQUE NOT NULL);
CREATE TABLE Artwork(
	ArtworkID INT PRIMARY KEY,
	Title VARCHAR(255) NOT NULL,
	ArtistID INT NOT NULL, 
	Description TEXT NOT NULL,
	CreationDate DATE NOT NULL,
	Medium VARCHAR(50),
	ImageURL VARCHAR(255) UNIQUE NOT NULL,
	FOREIGN KEY(ArtistID) REFERENCES Artist(ArtistID) ON DELETE CASCADE
);
CREATE TABLE Users(
	UserID INT PRIMARY KEY,
	Username VARCHAR(255) UNIQUE NOT NULL,
	Password VARCHAR(255) NOT NULL,
	Email VARCHAR(255) UNIQUE NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	DateOfBirth DATE NOT NULL,
	ProfilePicture VARCHAR(255),
	FavoriteArtworks INT NOT NULL,
	FOREIGN KEY(FavoriteArtworks) REFERENCES Artwork(ArtworkID) ON DELETE CASCADE
);
CREATE TABLE Gallery(
	GalleryID INT PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Description TEXT NOT NULL,
	Location VARCHAR(255) NOT NULL,
	Curator INT NOT NULL,
	OpeningHours TIME NOT NULL,
	FOREIGN KEY(Curator) REFERENCES Artist(ArtistID) ON DELETE CASCADE
);